sudo: required
services:
  - docker

before_install:
  - docker build -t amranprogramming/react-test -f ./client/Dockerfile.dev ./client

# Primary test running section. If anything here exits with a status code other than 0,
# then travis ci is going to assume our build fails
script:
  - docker run -e CI=true amranprogramming/react-test npm test

after_success:
  - docker build -t amranprogramming/multi-client ./client
  - docker build -t amranprogramming/multi-nginx ./nginx
  - docker build -t amranprogramming/multi-server ./server
  - docker build -t amranprogramming/multi-worker ./worker
  # Loginto our docker. Environment variables will be setup in travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push those images to dockerhub
  - docker push amranprogramming/multi-client
  - docker push amranprogramming/multi-nginx
  - docker push amranprogramming/multi-server
  - docker push amranprogramming/multi-worker
